#!/bin/sh
xrandr --output eDP-1 --mode 1920x1080 --pos 0x780 --rotate normal --rate 60.00 --output eDP-1-2 --off --output HDMI-1-1 --mode 2560x1440 --pos 1920x0 --rotate normal --rate 60.00 --output DP-1-1 --off --output DP-1-2 --off
