#!/bin/sh

echo DP-1-1: 2K @60hz \(primary\), HDM-1-1: 2K @60hz
xrandr --output eDP-1 --off --output eDP-1-2 --off --output HDMI-1-1 --mode 2560x1440 --rate 60.00 --pos 2560x0 --rotate normal --output DP-1-1 --off --output DP-1-2 --primary --mode 2560x1440 --rate 60.00 --pos 0x0 --rotate normal
